version: '3.8'

services:
  pokedex-app:
    image: aherom/pokedex-app
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
